Add the majority of the remaining optimizer passes
harlanhaskins/LLVMSwift pull request #23
Opened 2017-01-12 23:05 UTC by CodaFi

Commented passes require parameters that we cannot provide if we're
going to keep the existing lookup mechanism.

2017-01-12 23:07 UTC, harlanhaskins commented
I'd be up for not using this lookup mechanism then...

2017-01-12 23:10 UTC, CodaFi commented
It would be a shame to ditch it because of two pass families.  I think there's a way to be clever about pass the arguments through *and* maintaining the existing lookup scheme.  What that is, ¯\_(ツ)_/¯.

2017-01-12 23:14 UTC, harlanhaskins commented
Is a switch statement that much worse than a static dict? Pretty sure Swift will compile this into a jump table based on the descriminating bits in the enum, so it shouldn't have a performance penalty

2017-01-12 23:18 UTC, CodaFi commented
Mhm.  The alternative I was thinking of probably won't work.  OK, a big-honking jump table it will be.

2017-01-13 00:30 UTC, harlanhaskins requested changes
I...think this is worse. Hard to expand later.

2017-01-13 00:50 UTC, CodaFi commented
I'll revert this and leave the comments in so we can return to this.

2017-01-13 01:20 UTC, CodaFi commented
As long as the root is GTG:

⛵️

2017-01-13 01:20 UTC, merged