Added LLVM Object File support
harlanhaskins/LLVMSwift pull request #72
Opened 2017-02-19 00:46 UTC by harlanhaskins

2017-02-19 02:38 UTC, CodaFi commented
Travis seems to want to build LLVM from source...

2017-02-19 10:21 UTC, CodaFi requested changes

2017-02-19 10:21 UTC, CodaFi commented on Sources/LLVM/ObjectFile.swift
> +        self.llvm = llvm
Should be `LLVMSymbolIteratorRef`

2017-02-26 19:04 UTC, CodaFi approved these changes

2017-02-26 19:05 UTC, merged

2017-02-26 19:05 UTC, harlanhaskins commented
🚢 🇮🇹